//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Opgaver
{
	public String Chefkok
	{
		get;
		set;
	}

	public string Opryder
	{
		get;
		set;
	}

	public string Hjælpekok
	{
		get;
		set;
	}

	public  Måltid Måltid
	{
		get;
		set;
	}

}

