//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Gæst : hus
{
	public string Voksen
	{
		get
        {
            return Voksen;
        }
		set
        {
            Voksen = value;
        }
	}

	public string Barn
	{
		get
        {
            return Barn;
        }
		set
        {
            Barn = value;
        }
	}

	public string Ung
	{
		get
        {
            return Ung;
        }
		set
        {
            Ung = value;
        }
	}

}

